src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>QB_Id__c</fullName>
        <externalId>true</externalId>
        <label>QB Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Days_Outstanding__c</fullName>
        <formula>IF( NOT(ISNULL(Due_Date__c)), 


IF(Today()-Due_Date__c&lt;=30, &apos;0-30&apos;, 

 IF(Today()-Due_Date__c&gt;30  &amp;&amp; Today()-Due_Date__c&lt;=60, &apos;31-60&apos;, 

 IF(Today()-Due_Date__c&gt;60  &amp;&amp; Today()-Due_Date__c&lt;=90, &apos;61-90&apos;, 
 
IF(Today()-Due_Date__c&gt;90  &amp;&amp; Today()-Due_Date__c&lt;=120, &apos;91-120&apos;, &apos;&gt;121&apos;) 

) 

) 

)
, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Outstanding (Days)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QB_Id__c</fullName>
        <label>QB Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Billed__c * Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Bill (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Billed__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Billed</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mapper__c.object
<CustomObject>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quickbooks_Field_Name__c</fullName>
        <label>Quickbooks Field Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>Mapper</label>
    <nameField>
        <displayFormat>MP-{00000}</displayFormat>
        <label>Mapper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mappers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billed__c</fullName>
        <label>Billed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Manager_c__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>equals</operation>
                <value>New York Engineers</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Project Manager)</relationshipLabel>
        <relationshipName>OpportunitiesPM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal_Issued__c</fullName>
        <label>Proposal Issued</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QB_Id__c</fullName>
        <externalId>true</externalId>
        <label>QB Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_City__c</fullName>
        <label>Site City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Country__c</fullName>
        <label>Site Country</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_State__c</fullName>
        <label>Site State or Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Street_Address__c</fullName>
        <label>Site Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Zip_or_Code__c</fullName>
        <label>Site Zip or Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>proposal_issued_to_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal issued to 1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (proposal issued to 1)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QuickBooks Integration/objects/Opportunity.object
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>

src/objects/QB_Credentials__c.object
<CustomObject>
    <fields>
        <fullName>Access_token__c</fullName>
        <label>Access token</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RealMId__c</fullName>
        <label>RealMId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_token__c</fullName>
        <label>Refresh token</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>QB Credentials</label>
    <nameField>
        <displayFormat>QBC-{00000}</displayFormat>
        <label>QB Credential Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_InvoiceController.cls
@isTest
public class Test_InvoiceController {
    
    @TestSetup static void createData()
    {
        Test.startTest();
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());        
        Account a=new Account(Name='New York Engineers', Phone='0000000000', Website='http://www.test.com');
        insert a; 
        
        Contact con=new Contact(FirstName='Test', LastName='Contact', Email='test@test.com', Phone='000000000', Salutation='Mr', AccountId=a.Id);
        insert con;
        
        Opportunity opp=new Opportunity(Name='Test Opportunity', StageName='Closed Won', Proposal_Issued__c=System.today(), Amount=1000, 
                                        CloseDate=System.today(), AccountId=a.Id, Proposal_Issued_to_1__c=con.Id, Project_Manager_c__c=con.Id);
        insert opp;
        
        Opportunity opp1=new Opportunity(Name='TestOPP', StageName='Qualification', Proposal_Issued__c=System.today(), Amount=1000, 
                                         CloseDate=System.today(), AccountId=a.Id, Proposal_Issued_to_1__c=con.Id, Project_Manager_c__c=con.Id);
        insert opp1;
        
        //Insert new Invoice Attachment
        ContentVersion v = new ContentVersion();        
        Blob b=Blob.valueof('Test');        
        v.versionData =  b;
        v.title = 'Invoice#123';
        v.pathOnClient ='Invoice#123.pdf';
        v.Amount__c=1000;
        v.Balance__c=500;
        v.Due_Date__c=Date.valueOf('2016-08-08');
        v.QB_Id__c='1';        
        insert v;
        
        ContentVersion cdi=[SELECT Id, ContentDocumentId from ContentVersion where id=:v.id];
        ContentDocumentLink cdl=new ContentDocumentLink(ContentDocumentId=cdi.ContentDocumentId, LinkedEntityId=opp.Id, ShareType='I', Visibility = 'AllUsers');
        insert cdl;       
        
        ContentVersion v1 = new ContentVersion();        
        Blob b1=Blob.valueof('Test');        
        v1.versionData =  b1;
        v1.title = 'Invoice#123';
        v1.pathOnClient ='Invoice#123.pdf';
        v1.Amount__c=1000;
        v1.Balance__c=500;
        v1.Due_Date__c=Date.valueOf('2016-08-08');
        v1.QB_Id__c='1';       
        insert v1;
        
        ContentVersion cdi1=[SELECT Id, ContentDocumentId from ContentVersion where id=:v1.id];
        ContentDocumentLink cdl1=new ContentDocumentLink(ContentDocumentId=cdi.ContentDocumentId, LinkedEntityId=opp1.Id, ShareType='I', Visibility = 'AllUsers');
        insert cdl1;
        
        List<Mapper__c> mappingList=new List<Mapper__c>();
        mappingList.add(new Mapper__c(Field_Name__c='name', Quickbooks_Field_Name__c='DisplayName', Object__c='Opportunity'));
        mappingList.add(new Mapper__c(Field_Name__c='name', Quickbooks_Field_Name__c='CompanyName', Object__c='Opportunity'));
        mappingList.add(new Mapper__c(Field_Name__c='name', Quickbooks_Field_Name__c='FullyQualifiedName', Object__c='Opportunity'));  
        mappingList.add(new Mapper__c(Field_Name__c='name', Quickbooks_Field_Name__c='FullyQualifiedName', Object__c='Account'));            
        mappingList.add(new Mapper__c(Field_Name__c='name', Quickbooks_Field_Name__c='CompanyName', Object__c='Account'));            
        mappingList.add(new Mapper__c(Field_Name__c='name', Quickbooks_Field_Name__c='DisplayName', Object__c='Account'));            
        mappingList.add(new Mapper__c(Field_Name__c='website', Quickbooks_Field_Name__c='WebAddr', Object__c='Account'));            
        mappingList.add(new Mapper__c(Field_Name__c='proposal_issued_to_1__c', Quickbooks_Field_Name__c='ContactDetails', Object__c='Opportunity'));         
        mappingList.add(new Mapper__c( Field_Name__c='shippingstreet', Quickbooks_Field_Name__c='ShipLine1', Object__c='Account'));   
        mappingList.add(new Mapper__c(Field_Name__c='shippingstate', Quickbooks_Field_Name__c='ShipCountrySubDivisionCode', Object__c='Account')); 
        mappingList.add(new Mapper__c(Field_Name__c='shippingpostalcode', Quickbooks_Field_Name__c='ShipPostalCode', Object__c='Account'));
        mappingList.add(new Mapper__c(Field_Name__c='shippingcity', Quickbooks_Field_Name__c='ShipCity', Object__c='Account')); 
        mappingList.add(new Mapper__c(Field_Name__c='shippingcountry', Quickbooks_Field_Name__c='ShipCountry', Object__c='Account')); 
        mappingList.add(new Mapper__c(Field_Name__c='billingstreet', Quickbooks_Field_Name__c='BillLine1', Object__c='Account'));   
        mappingList.add(new Mapper__c(Field_Name__c='billingstate', Quickbooks_Field_Name__c='BillCountrySubDivisionCode', Object__c='Account')); 
        mappingList.add(new Mapper__c(Field_Name__c='billingpostalcode', Quickbooks_Field_Name__c='BillPostalCode', Object__c='Account'));
        mappingList.add(new Mapper__c(Field_Name__c='billingcity', Quickbooks_Field_Name__c='BillCity', Object__c='Account')); 
        mappingList.add(new Mapper__c(Field_Name__c='billingcountry', Quickbooks_Field_Name__c='BillCountry', Object__c='Account')); 
        mappingList.add(new Mapper__c(Field_Name__c='Site_Street_Address__c	', Quickbooks_Field_Name__c='BillLine1', Object__c='Opportunity'));            
        mappingList.add(new Mapper__c(Field_Name__c='site_zip_or_code__c', Quickbooks_Field_Name__c='BillPostalCode', Object__c='Opportunity'));
        mappingList.add(new Mapper__c(Field_Name__c='Site_State__c', Quickbooks_Field_Name__c='BillCountrySubDivisionCode', Object__c='Opportunity')); 
        mappingList.add(new Mapper__c(Field_Name__c='site_country__c', Quickbooks_Field_Name__c='BillCountry', Object__c='Opportunity')); 
        mappingList.add(new Mapper__c(Field_Name__c='Site_City__c', Quickbooks_Field_Name__c='BillCity', Object__c='Opportunity'));   
        mappingList.add(new Mapper__c(Field_Name__c='Site_Street_Address__c	', Quickbooks_Field_Name__c='ShipLine1', Object__c='Opportunity'));            
        mappingList.add(new Mapper__c(Field_Name__c='site_zip_or_code__c', Quickbooks_Field_Name__c='ShipPostalCode', Object__c='Opportunity'));
        mappingList.add(new Mapper__c(Field_Name__c='Site_State__c', Quickbooks_Field_Name__c='ShipCountrySubDivisionCode', Object__c='Opportunity')); 
        mappingList.add(new Mapper__c(Field_Name__c='site_country__c', Quickbooks_Field_Name__c='ShipCountry', Object__c='Opportunity')); 
        mappingList.add(new Mapper__c(Field_Name__c='Site_City__c', Quickbooks_Field_Name__c='ShipCity', Object__c='Opportunity')); 
        mappingList.add(new Mapper__c(Field_Name__c='phone', Quickbooks_Field_Name__c='AlternatePhone', Object__c='Account'));   
        mappingList.add(new Mapper__c(Field_Name__c='phone', Quickbooks_Field_Name__c='AlternatePhone', Object__c='Account'));
        insert mappingList;
        
    }
    
    @isTest static void TestIssuedInvoiceReportController()
    {
        Test.startTest();
        List<QB_Credentials__c> qbcList=[Select Id, Access_token__c, Refresh_token__c,
                                         realmid__c from QB_Credentials__c];
        Account a=[Select Id, Name, Phone, Website, Qb_Id__c from Account where name='New York Engineers'];
        Opportunity opp=[Select Id, Name, QB_Id__c from Opportunity where name='Test Opportunity'];
        List<ContentDocumentLink> issuedInvoicesLinks=[Select Id, ContentDocumentId,LinkedEntityId, LinkedEntity.name from ContentDocumentLink where 
                                                       LinkedEntityId =:opp.Id and ContentDocument.title like 'Invoice%'];
        List<ContentVersion> issuedInvoices=[Select Id, Title, Amount__c, ContentDocumentId, Days_Outstanding__c from ContentVersion where ContentDocumentId=:issuedInvoicesLinks[0].ContentDocumentId
                                             and title like 'Invoice%' order by createddate asc];
        IssuedInvoiceReportController iirc=new IssuedInvoiceReportController();
        Test.stopTest();
        
    }
    
    @isTest static void TestInvoiceController()
    {
        Test.startTest();
        List<QB_Credentials__c> qbcList=[Select Id, Access_token__c, Refresh_token__c,
                                         realmid__c from QB_Credentials__c];
        Account a=[Select Id, Name, Phone, Website, Qb_Id__c from Account where name='New York Engineers'];
        Opportunity opp=[Select Id, Name, QB_Id__c from Opportunity where name='Test Opportunity'];
        Test.setCurrentPage(new pageReference('/apex/Invoice?id='+opp.id));
        List<ContentDocumentLink> issuedInvoicesLinks=[Select Id, ContentDocumentId,LinkedEntityId, LinkedEntity.name from ContentDocumentLink where 
                                                       LinkedEntityId =:opp.Id and ContentDocument.title like 'Invoice%'];
        List<ContentVersion> issuedInvoices=[Select Id, Title, Amount__c, ContentDocumentId, Days_Outstanding__c from ContentVersion where ContentDocumentId=:issuedInvoicesLinks[0].ContentDocumentId
                                             and title like 'Invoice%' order by createddate asc];
        InvoiceController ic=new InvoiceController(new ApexPages.StandardController(opp));
        ic.itemindex=1;
        ic.getInvoices();
        ic.getIssuedInvoices();
        ic.addMore();
        ic.RemoveItem();
        ic.save();
        ic.returnPage();
        ic.invoiceBillStatus();
        ic.getIsEnabled();
        ic.getShowDialogue();
        ic.closePopeUp();
        ic.RemoveBilledItem();
        ic.RefreshWindow();
        ic.resetFlags();
        InvoiceController.getDateFromString('2019-03-29T08:31:46-07:00');
        Test.stopTest();
    }  
        
    @isTest static void TestInvoiceStageNotClosedWon()
    {
        Test.startTest();
        List<QB_Credentials__c> qbcList=[Select Id, Access_token__c, Refresh_token__c,
                                         realmid__c from QB_Credentials__c];
        Account a=[Select Id, Name, Phone, Website, Qb_Id__c from Account where name='New York Engineers'];
        Opportunity opp=[Select Id, Name, QB_Id__c from Opportunity where name='TestOPP'];
        Test.setCurrentPage(new pageReference('/apex/Invoice?id='+opp.id));
        List<ContentDocumentLink> issuedInvoicesLinks=[Select Id, ContentDocumentId,LinkedEntityId, LinkedEntity.name from ContentDocumentLink where 
                                                       LinkedEntityId =:opp.Id and ContentDocument.title like 'Invoice%'];
        List<ContentVersion> issuedInvoices=[Select Id, Title, Amount__c, ContentDocumentId, Days_Outstanding__c from ContentVersion where ContentDocumentId=:issuedInvoicesLinks[0].ContentDocumentId
                                             and title like 'Invoice%' order by createddate asc];
        Invoice__c inv=[Select Id, Bill__c, Amount__c from Invoice__c where Opportunity__c=:opp.Id and name='Schematic Design' Limit 1];
        inv.Billed__c=50;
        update inv;           
        
        InvoiceController ic=new InvoiceController(new ApexPages.StandardController(opp));
        ic.itemindex=1;
        ic.getInvoices();
        ic.getIssuedInvoices();
        ic.addMore();
        ic.RemoveItem();
        ic.save();
        ic.returnPage();
        ic.invoiceBillStatus();
        ic.getIsEnabled();
        ic.getShowDialogue();
        ic.closePopeUp();
        ic.RemoveBilledItem();
        ic.RefreshWindow();
        ic.resetFlags();
        InvoiceController.getDateFromString('2019-03-29T08:31:46-07:00');
        Test.stopTest();
    }  
        
    @isTest static void TestICrWithBillNonZero()
    {
        Test.startTest();
        List<QB_Credentials__c> qbcList=[Select Id, Access_token__c, Refresh_token__c,
                                         realmid__c from QB_Credentials__c];
        Account a=[Select Id, Name, Phone, Website, Qb_Id__c from Account where name='New York Engineers'];
        Opportunity opp=[Select Id, Name, QB_Id__c from Opportunity where name='Test Opportunity'];
        Test.setCurrentPage(new pageReference('/apex/Invoice?id='+opp.id));
        List<ContentDocumentLink> issuedInvoicesLinks=[Select Id, ContentDocumentId,LinkedEntityId, LinkedEntity.name from ContentDocumentLink where 
                                                       LinkedEntityId =:opp.Id and ContentDocument.title like 'Invoice%'];     
        List<ContentVersion> issuedInvoices=[Select Id, Title, Amount__c, ContentDocumentId, Days_Outstanding__c from ContentVersion where ContentDocumentId=:issuedInvoicesLinks[0].ContentDocumentId
                                             and title like 'Invoice%' order by createddate asc];
        Invoice__c inv=[Select Id, Bill__c, Amount__c from Invoice__c where Opportunity__c=:opp.Id and name='Schematic Design' Limit 1];
        inv.Name = null;
        inv.Billed__c=0;
        inv.Bill__c = 100;
        inv.Fee__c = 10;
        update inv;          
        
        Invoice__c inv1=[Select Id, Bill__c, Amount__c from Invoice__c where Opportunity__c=:opp.Id and name='Punchlist' Limit 1];
        inv1.Name = null;
        inv1.Billed__c=0;
        inv1.Bill__c = -100;
        inv1.Fee__c = 10;
        update inv1;          
        
        InvoiceController ic=new InvoiceController(new ApexPages.StandardController(opp));
        ic.itemindex=1;        
        ic.save();        
        InvoiceController.getDateFromString('2019-03-29T08:31:46-07:00');
        InvoiceController.testPass();
        Test.stopTest();
    }  
}