src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>QB_Id__c</fullName>
        <externalId>true</externalId>
        <label>QB Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Billed__c * Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Bill (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Billed__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Billed</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Sync__c.object
<CustomObject>
    <description>QB SF Invoice Sync</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Sync</relationshipLabel>
        <relationshipName>Invoice_Sync</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QB_Id__c</fullName>
        <label>QB Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Invoice Sync</label>
    <nameField>
        <displayFormat>IS-{00000}</displayFormat>
        <label>Invoice Sync Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Sync</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mapper__c.object
<CustomObject>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quickbooks_Field_Name__c</fullName>
        <label>Quickbooks Field Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>Mapper</label>
    <nameField>
        <displayFormat>MP-{00000}</displayFormat>
        <label>Mapper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mappers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billed__c</fullName>
        <label>Billed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Proposal_Issued__c</fullName>
        <label>Proposal Issued</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QB_Id__c</fullName>
        <externalId>true</externalId>
        <label>QB Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_City__c</fullName>
        <label>Site City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Country__c</fullName>
        <label>Site Country</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_State__c</fullName>
        <label>Site State or Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Street_Address__c</fullName>
        <label>Site Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Zip_or_Code__c</fullName>
        <label>Site Zip or Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>proposal_issued_to_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal issued to 1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (proposal issued to 1)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QB_Credentials__c.object
<CustomObject>
    <fields>
        <fullName>Access_token__c</fullName>
        <label>Access token</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RealMId__c</fullName>
        <label>RealMId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_token__c</fullName>
        <label>Refresh token</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>QB Credentials</label>
    <nameField>
        <displayFormat>QBC-{00000}</displayFormat>
        <label>QB Credential Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_QuickbookSyncer.cls
@isTest
public class Test_QuickbookSyncer {
    
    @TestSetup static void createData()
    {
        List<Mapper__c> mappingList=new List<Mapper__c>();
        
        mappingList.add(new Mapper__c(Field_Name__c='name', Quickbooks_Field_Name__c='DisplayName', Object__c='Opportunity'));
        mappingList.add(new Mapper__c(Field_Name__c='name', Quickbooks_Field_Name__c='CompanyName', Object__c='Opportunity'));
        mappingList.add(new Mapper__c(Field_Name__c='name', Quickbooks_Field_Name__c='FullyQualifiedName', Object__c='Opportunity'));  
        
        mappingList.add(new Mapper__c(Field_Name__c='name', Quickbooks_Field_Name__c='FullyQualifiedName', Object__c='Account'));            
        mappingList.add(new Mapper__c(Field_Name__c='name', Quickbooks_Field_Name__c='CompanyName', Object__c='Account'));            
        mappingList.add(new Mapper__c(Field_Name__c='name', Quickbooks_Field_Name__c='DisplayName', Object__c='Account'));            
        
        
        mappingList.add(new Mapper__c(Field_Name__c='website', Quickbooks_Field_Name__c='WebAddr', Object__c='Account'));            
        mappingList.add(new Mapper__c(Field_Name__c='proposal_issued_to_1__c', Quickbooks_Field_Name__c='ContactDetails', Object__c='Opportunity'));            
        
        //    mappingList.add(new Mapper__c(Field_Name__c='Invoice_CC_1__c', Quickbooks_Field_Name__c='ContactDetails', Object__c='Opportunity'));            
        
        
        mappingList.add(new Mapper__c( Field_Name__c='shippingstreet', Quickbooks_Field_Name__c='ShipLine1', Object__c='Account'));   
        mappingList.add(new Mapper__c(Field_Name__c='shippingstate', Quickbooks_Field_Name__c='ShipCountrySubDivisionCode', Object__c='Account')); 
        mappingList.add(new Mapper__c(Field_Name__c='shippingpostalcode', Quickbooks_Field_Name__c='ShipPostalCode', Object__c='Account'));
        mappingList.add(new Mapper__c(Field_Name__c='shippingcity', Quickbooks_Field_Name__c='ShipCity', Object__c='Account')); 
        mappingList.add(new Mapper__c(Field_Name__c='shippingcountry', Quickbooks_Field_Name__c='ShipCountry', Object__c='Account')); 
        
        mappingList.add(new Mapper__c(Field_Name__c='billingstreet', Quickbooks_Field_Name__c='BillLine1', Object__c='Account'));   
        mappingList.add(new Mapper__c(Field_Name__c='billingstate', Quickbooks_Field_Name__c='BillCountrySubDivisionCode', Object__c='Account')); 
        mappingList.add(new Mapper__c(Field_Name__c='billingpostalcode', Quickbooks_Field_Name__c='BillPostalCode', Object__c='Account'));
        mappingList.add(new Mapper__c(Field_Name__c='billingcity', Quickbooks_Field_Name__c='BillCity', Object__c='Account')); 
        mappingList.add(new Mapper__c(Field_Name__c='billingcountry', Quickbooks_Field_Name__c='BillCountry', Object__c='Account')); 
        
        mappingList.add(new Mapper__c(Field_Name__c='Site_Street_Address__c	', Quickbooks_Field_Name__c='BillLine1', Object__c='Opportunity'));            
        mappingList.add(new Mapper__c(Field_Name__c='site_zip_or_code__c', Quickbooks_Field_Name__c='BillPostalCode', Object__c='Opportunity'));
        mappingList.add(new Mapper__c(Field_Name__c='Site_State__c', Quickbooks_Field_Name__c='BillCountrySubDivisionCode', Object__c='Opportunity')); 
        mappingList.add(new Mapper__c(Field_Name__c='site_country__c', Quickbooks_Field_Name__c='BillCountry', Object__c='Opportunity')); 
        mappingList.add(new Mapper__c(Field_Name__c='Site_City__c', Quickbooks_Field_Name__c='BillCity', Object__c='Opportunity'));   
        
        mappingList.add(new Mapper__c(Field_Name__c='Site_Street_Address__c	', Quickbooks_Field_Name__c='ShipLine1', Object__c='Opportunity'));            
        mappingList.add(new Mapper__c(Field_Name__c='site_zip_or_code__c', Quickbooks_Field_Name__c='ShipPostalCode', Object__c='Opportunity'));
        mappingList.add(new Mapper__c(Field_Name__c='Site_State__c', Quickbooks_Field_Name__c='ShipCountrySubDivisionCode', Object__c='Opportunity')); 
        mappingList.add(new Mapper__c(Field_Name__c='site_country__c', Quickbooks_Field_Name__c='ShipCountry', Object__c='Opportunity')); 
        mappingList.add(new Mapper__c(Field_Name__c='Site_City__c', Quickbooks_Field_Name__c='ShipCity', Object__c='Opportunity')); 
        
        mappingList.add(new Mapper__c(Field_Name__c='phone', Quickbooks_Field_Name__c='AlternatePhone', Object__c='Account'));   
        mappingList.add(new Mapper__c(Field_Name__c='phone', Quickbooks_Field_Name__c='AlternatePhone', Object__c='Account'));
        
        insert mappingList;
        
        QB_Credentials__c qb=new QB_Credentials__c(Access_token__c='123', Refresh_token__c='123', realmid__c='123');
        insert qb;
        
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Account a=new Account(Name='Test Account', Phone='0000000000', Website='http://www.test.com');
        insert a;
        
        Contact con=new Contact(FirstName='Test', LastName='Contact', Email='test@test.com', Phone='000000000', Salutation='Mr');
        insert con;
        
        Opportunity opp=new Opportunity(Name='Test Opportunity', StageName='Closed Won', Proposal_Issued__c=System.today(), Amount=1000,
                                        CloseDate=System.today(), AccountId=a.Id, Proposal_Issued_to_1__c=con.Id);
        
        //   Opportunity opp=new Opportunity(Name='Test Opportunity', StageName='Closed Won', Proposal_Issued__c=System.today(), Amount=1000,
        //                                CloseDate=System.today(), AccountId=a.Id, Invoice_CC_1__c=con.Id);
        
        insert opp;
        List<Invoice__c> inv = [Select Id from Invoice__c where Opportunity__c = :opp.Id and Name= 'Schematic Design'];
        
        Invoice_Sync__c invSync=new Invoice_Sync__c(Invoice__c=inv[0].id, Amount__c=150, Qb_Id__c='1');
        insert invSync;
        
    }
    
    @isTest static void TestSendUpdateCustomer()
    {
        Test.startTest();
        
        List<Mapper__c> mappingList=[Select Id, Field_Name__c, Quickbooks_Field_Name__c, Object__c from Mapper__c ];
        
        List<QB_Credentials__c> qbcList=[Select Id, Access_token__c, Refresh_token__c,
                                         realmid__c from QB_Credentials__c];
        
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Account a=[Select Id, Name, Phone, Website, Qb_Id__c from Account where name='Test Account'];
        
        a.Name='Test Account Update';
        a.QB_Id__c='1';
        update a;
        
        QuickbookApiCrud.testPass();
        Test.stopTest();
    }
    
    @isTest static void TestSendUpdateSubCustomer()
    {
        Test.startTest();
        
        List<Mapper__c> mappingList=[Select Id, Field_Name__c, Quickbooks_Field_Name__c, Object__c from Mapper__c ];
        
        List<QB_Credentials__c> qbcList=[Select Id, Access_token__c, Refresh_token__c,
                                         realmid__c from QB_Credentials__c];
        
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Account a=[Select Id, Name, Phone, Website, Qb_Id__c from Account where name='Test Account'];
        Opportunity opp=[Select Id, Name, QB_Id__c from Opportunity where name='Test Opportunity'];
        
        opp.Name='Test Opportunity Update';
        opp.QB_Id__c='1';
        update opp;
        
        Contact con=[Select Id, Lastname from Contact where lastname='Contact'];
        con.lastname='Contact Update';
        update con;
        
        Test.stopTest();
        
    }
    
    @isTest static void TestSendInvoice()
    {
        Test.startTest();
        
        List<Mapper__c> mappingList=[Select Id, Field_Name__c, Quickbooks_Field_Name__c, Object__c from Mapper__c ];
        
        List<QB_Credentials__c> qbcList=[Select Id, Access_token__c, Refresh_token__c,
                                         realmid__c from QB_Credentials__c];
        
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Opportunity opp=[Select Id, Name, QB_Id__c from Opportunity where name='Test Opportunity'];
        
        List <Invoice__c> lst_inv=[Select Id, Bill__c from Invoice__c where Opportunity__c=:opp.Id and name='Schematic Design'];
        
        Id invId ;
        if(lst_inv.size()>0){
            lst_inv.get(0).Billed__c=50;         
            invId = lst_inv.get(0).id;
            update lst_inv;      
        }
        
        Test.stopTest();
        
    }
    
    @isTest static void TestScheduler()
    {
        
        // Set mock callout class 
        
        Opportunity opp=[Select Id, Name, QB_Id__c from Opportunity where name='Test Opportunity'];
        
        List <Invoice__c> lst_inv=[Select Id, Bill__c, Amount__c from Invoice__c where Opportunity__c=:opp.Id and name='Schematic Design'];
        Id invId ;
        if(lst_inv.size()>0){
            lst_inv.get(0).Billed__c=50;         
            invId = lst_inv.get(0).id;
            
            
            update lst_inv;
            Invoice_Sync__c invSync=new Invoice_Sync__c(Invoice__c=invId, Amount__c=150, Qb_Id__c='1');
            insert invSync; 
        }
        Test.startTest();
        QuickbookScheduler qbs = new QuickbookScheduler();
        qbs.testPass();
        
        //QuickbookApiCrud.setInvoiceEmail(inv,null,[Select id,Quickbooks_Field_Name__c,Object__c,Field_Name__c from Mapper__c]);
        String sch = '0 0 23 * * ?';  
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        //system.schedule('QB Scheduler', sch, qbs);
        Test.stopTest();    
    }
}