src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>QB_Id__c</fullName>
        <externalId>true</externalId>
        <label>QB Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Project_Manager_c__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>equals</operation>
                <value>New York Engineers</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Project Manager)</relationshipLabel>
        <relationshipName>OpportunitiesPM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal_Issued__c</fullName>
        <label>Proposal Issued</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QB_Id__c</fullName>
        <externalId>true</externalId>
        <label>QB Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>proposal_issued_to_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal issued to 1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (proposal issued to 1)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_ExistingRecordScript.cls
@isTest
public class Test_ExistingRecordScript {
    
    @TestSetup static void createData()
    {
        Account a=new Account(Name='New York Engineers', Phone='0000000000', Website='http://www.test.com');
        insert a;
        
        Contact con=new Contact(FirstName='Test', LastName='Contact', Email='test@test.com', Phone='000000000', Salutation='Mr', AccountId=a.Id);
        insert con;
        
        Opportunity opp=new Opportunity(Name='Test Opportunity', StageName='Closed Won', Proposal_Issued__c=System.today(), Amount=1000, Qb_Id__c='1',
                                        CloseDate=System.today(), AccountId=a.Id, Proposal_Issued_to_1__c=con.Id, Project_Manager_c__c=con.Id);
        insert opp;
        
        List<Invoice__c> invoiceList = [Select Id from Invoice__c where Opportunity__c=:opp.Id];
        delete invoiceList;
    }
    
    @isTest
    public static void TriggerOnCustomEventAction()
    {
        List<Opportunity> oppList=[Select Id, Name from Opportunity];
        
        ExistingRecordScript batch=new ExistingRecordScript();
        Database.executeBatch(batch, 1000);
    }
    
}