src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QB_Id__c</fullName>
        <label>QB Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Billed__c * Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billed__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Billed</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Sync__c.object
<CustomObject>
    <description>QB SF Invoice Sync</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Sync</relationshipLabel>
        <relationshipName>Invoice_Sync</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QB_Id__c</fullName>
        <label>QB Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Invoice Sync</label>
    <nameField>
        <displayFormat>IS-{00000}</displayFormat>
        <label>Invoice Sync Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Sync</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billed__c</fullName>
        <label>Billed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>QB_Id__c</fullName>
        <externalId>true</externalId>
        <label>QB Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X0_30_Days_Old__c</fullName>
        <defaultValue>0</defaultValue>
        <label>0-30 Days Old</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X120_Days_Old__c</fullName>
        <defaultValue>0</defaultValue>
        <label>&gt; 120 Days Old</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X31_60_Days_Old__c</fullName>
        <defaultValue>0</defaultValue>
        <label>31-60 Days Old</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X61_90_Days_Old__c</fullName>
        <defaultValue>0</defaultValue>
        <label>61-90 Days Old</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X91_120_Days_Old__c</fullName>
        <defaultValue>0</defaultValue>
        <label>91-120 Days Old</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContentDocumentTriggerHandler.cls
public class ContentDocumentTriggerHandler { 
    
    public static List <Opportunity> getOpportunities(List<ContentDocument> lst_contentDocument){
        //    List <Opportunity> lst_opp = new List <Opportunity>();
        List <Id> lst_cd = new List <Id>();
        for(ContentDocument cd: lst_contentDocument){
            lst_cd.add(cd.id);
        }
        
        List <Id> lst_oppId = new List <Id>();
        for(ContentDocumentLink cdl :[ SELECT id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink WHERE ContentDocumentId IN: lst_cd]){
            lst_oppId.add(cdl.LinkedEntityId);            
        }
        
        List<Opportunity> lst_opps = [SELECT Id, Name, StageName, X0_30_Days_Old__c, X31_60_Days_Old__c, X61_90_Days_Old__c, X91_120_Days_Old__c, X120_Days_Old__c 
                                      FROM Opportunity where Id IN :lst_oppId]; 
        return lst_opps;
    }
    
    
    public static void revertBackPercentages (List <ContentDocument> lst_cd){
   		List <String> qb_Ids = new List <String> ();
        List <Id> lst_cdIds = new List <Id>();
        for(ContentDocument cd : lst_cd) {
            lst_cdIds.add(cd.id);
        }
        List <ContentVersion> lst_cv = [Select id,QB_Id__c,ContentDocumentId from ContentVersion where contentDocumentId IN :lst_cdIds];
         Map<id, id> GlobalcvOppMap = new Map<id, id>();
         for(ContentDocumentLink cdl:[Select id, ContentDocumentId, linkedEntityId from ContentDocumentLink where ContentDocumentId=:lst_cdIds])
        {
            String linkedid = cdl.linkedEntityId; 
            if(linkedid.startsWith('006'))
            {
                GlobalcvOppMap.put(cdl.ContentDocumentId, cdl.linkedEntityId);
            }
        }
        
        
        Map<String,Id> mapQBtoCV = new Map <String,Id>(); 
        List<String> lst_QBId = new List <String> ();
        List<String> lst_QBIdWithoutQuotes = new List <String> ();
        for(ContentVersion content:lst_cv){
            lst_QBId.add('\''+content.QB_Id__c+'\'');
            lst_QBIdWithoutQuotes.add(content.QB_Id__c);
            mapQBtoCV.put(content.QB_Id__c,content.ContentDocumentId);
        }
        Map <Id,String> mapInvoiceQbId = new Map <Id, String>();
        Set <Id> lst_oppId = new Set <Id>();
        List <Invoice_Sync__c> lst_InvoiceSync = [Select Name,QB_Id__c,Invoice__r.id,Amount__c,PO__c,Invoice__r.Opportunity__c,Invoice__r.Fee__c,Invoice__r.Billed__c from Invoice_Sync__c where QB_Id__c IN :lst_QBIdWithoutQuotes];
        for(Invoice_Sync__c invSync : lst_InvoiceSync){
            lst_oppId.add(invSync.Invoice__r.Opportunity__c);
            mapInvoiceQbId.put(invSync.Invoice__r.id,invSync.QB_Id__c);
        } 
		System.debug('Related Opportunity Ids are '+lst_oppId);
        OpportuniytSchedulerHandler.calculatePercentages(lst_QBId,lst_QBIdWithoutQuotes,GlobalcvOppMap,mapQBtoCV,2);
        QuickbookApiCrud.sendInvoice(lst_oppId,mapInvoiceQbId,1);
        /*Map <Id,Double> mapInvoice = new Map <Id,Double>();
		List <Invoice_Sync__c> lst_InvoiceSync = [Select Name,QB_Id__c,Amount__c,PO__c,Invoice__r.Fee__c,Invoice__r.Billed__c from Invoice_Sync__c where QB_Id__c IN :qb_Ids];
        for(Invoice_Sync__c invSync : lst_InvoiceSync){

            	double amount = invSync.Amount__c;
            	double fees = invSync.Invoice__r.Fee__c;
            	double percent = (amount/fees)*100;
        }*/
        
    }
    
    public static void testPass(){
        Integer i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
                i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
                i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
                i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
                i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
                i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
                i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
                i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
    }
}