src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Days_Outstanding__c</fullName>
        <formula>IF( NOT(ISNULL(Due_Date__c)), 


IF(Today()-Due_Date__c&lt;=30, &apos;0-30&apos;, 

 IF(Today()-Due_Date__c&gt;30  &amp;&amp; Today()-Due_Date__c&lt;=60, &apos;31-60&apos;, 

 IF(Today()-Due_Date__c&gt;60  &amp;&amp; Today()-Due_Date__c&lt;=90, &apos;61-90&apos;, 
 
IF(Today()-Due_Date__c&gt;90  &amp;&amp; Today()-Due_Date__c&lt;=120, &apos;91-120&apos;, &apos;&gt;121&apos;) 

) 

) 

)
, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Outstanding (Days)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QB_Id__c</fullName>
        <label>QB Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Balance__c =0 ,&apos;Paid&apos;,
IF(Balance__c&gt;0 &amp;&amp; Balance__c&lt;Amount__c, &apos;Partial&apos;,
IF(Today()-Due_Date__c&gt;0, &apos;Overdue&apos;,  &apos;Open&apos;) ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Deleted_QB_Ids__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>QB_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>QB ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Deleted Contents QB Ids</label>
</CustomObject>

src/objects/FeeStorage__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>FeeStorages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>FeeStorages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scheduled Invoice</label>
    <nameField>
        <label>FeeStorage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Billed__c * Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_Frame__c</fullName>
        <label>Time Frame (Weeks)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bid_Documents_Construction_Documents__c</fullName>
        <label>Bid Documents/ Construction Documents</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Construction_Admin__c</fullName>
        <label>Construction Admin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DOB_Approval_1__c</fullName>
        <label>DOB Approval 1</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DOB_Filing_Set_1__c</fullName>
        <label>DOB Filing Set 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Punchlist__c</fullName>
        <label>Punchlist</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>QB_Id__c</fullName>
        <externalId>true</externalId>
        <label>QB Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retainer1__c</fullName>
        <label>Retainer1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Schematic_Design_SD_1__c</fullName>
        <label>Schematic Design (SD) 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TF_CA__c</fullName>
        <defaultValue>52</defaultValue>
        <label>TF - CA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TF_DD_CD__c</fullName>
        <defaultValue>4</defaultValue>
        <label>TF - DD/CD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TF_DOB_App__c</fullName>
        <defaultValue>8</defaultValue>
        <label>TF - DOB App</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TF_DOB_Filing__c</fullName>
        <defaultValue>6</defaultValue>
        <label>TF - DOB Filing</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TF_Punch__c</fullName>
        <defaultValue>2</defaultValue>
        <label>TF - Punch</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TF_SD__c</fullName>
        <defaultValue>4</defaultValue>
        <label>TF - SD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ResetOppController.cls
public class ResetOppController {
    Id oppId;
    
    public ResetOppController(ApexPages.StandardController stdController){
        oppId = stdController.getRecord().Id;
    }
    
    public PageReference resetOpp(){
        delete [Select Id from Invoice__c where Opportunity__c = :oppId];
        delete [Select Id from FeeStorage__c where Opportunity__c = :oppId];
        createNewInvoices();
        deleteIssuedInvoices();
        return redirectToRecord();
    }
    
    public void createNewInvoices(){
        List<Invoice__c> defaultInvoices=new List<Invoice__c>();
        Opportunity targetOpp = [SELECT Id, Construction_Admin__c, DOB_Filing_Set_1__c, DOB_Approval_1__c, Retainer1__c, TF_CA__c, TF_DD_CD__c, TF_DOB_App__c,
                                 TF_DOB_Filing__c, TF_Punch__c, TF_SD__c, Schematic_Design_SD_1__c, Bid_Documents_Construction_Documents__c, Punchlist__c 
                                 FROM Opportunity
                                Where Id = :oppId];
        defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_1, Time_Frame__c='To Start Project', Default__c=true,
                                           Fee__c=targetOpp.Retainer1__c, Opportunity__c=oppId));
        
        defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_2, Time_Frame__c=String.valueof(targetOpp.TF_SD__c), Default__c=true,
                                           Fee__c=targetOpp.Schematic_Design_SD_1__c, Opportunity__c=oppId));
        
        defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_3, Time_Frame__c=String.valueof(targetOpp.TF_DOB_Filing__c), Default__c=true,
                                           Fee__c=targetOpp.DOB_Filing_Set_1__c, Opportunity__c=oppId));
        
        defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_4, Time_Frame__c=String.valueof(targetOpp.TF_DOB_App__c), Default__c=true,
                                           Fee__c=targetOpp.DOB_Approval_1__c, Opportunity__c=oppId));
        
        defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_5, Time_Frame__c=String.valueof(targetOpp.TF_DD_CD__c), Default__c=true,
                                           Fee__c=targetOpp.Bid_Documents_Construction_Documents__c, Opportunity__c=oppId));
        
        defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_6, Time_Frame__c=String.valueof(targetOpp.TF_CA__c), Default__c=true,
                                           Fee__c=targetOpp.Construction_Admin__c, Opportunity__c=oppId));
        
        defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_7, Time_Frame__c=String.valueof(targetOpp.TF_Punch__c), Default__c=true,
                                           Fee__c=targetOpp.Punchlist__c, Opportunity__c=oppId));
        
        insert defaultInvoices;
    }
    
    public void deleteIssuedInvoices(){
        List<Id> contentLinkIds=new List<Id>();
        List<Id> idsToDelete=new List<Id>();
        List<Deleted_QB_Ids__c> deletedIds = new List<Deleted_QB_Ids__c>();
        List<ContentDocumentLink> issuedInvoicesLinks=[Select Id, ContentDocumentId from ContentDocumentLink where LinkedEntityId=:oppId];
        for(ContentDocumentLink cdl:issuedInvoicesLinks){
            contentLinkIds.add(cdl.ContentDocumentId);
        }
        
        for(ContentVersion cvs:[SELECT Id, title, ContentDocumentId, Amount__c,Status__c, Days_Outstanding__c,QB_Id__c from ContentVersion where contentdocumentid=:contentLinkIds]){
            if(cvs.title.contains('Invoice#')){
                idsToDelete.add(cvs.ContentDocumentId);
                deletedIds.add(new Deleted_QB_Ids__c(Name=cvs.QB_Id__c,QB_ID__c = cvs.QB_Id__c));
            }
        }
        try{
            insert deletedIds;
        }
        catch(Exception e){
            System.debug('Exception : ' + e.getMessage());
        }
        delete [Select Id from ContentDocument where Id =:idsToDelete];
    }
    
    public PageReference redirectToRecord(){
        PageReference reference = new PageReference('/'+oppId);
        reference.setRedirect(true);
        return reference;
    }

}