src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Days_Outstanding__c</fullName>
        <formula>IF( NOT(ISNULL(Due_Date__c)), 


IF(Today()-Due_Date__c&lt;=30, &apos;0-30&apos;, 

 IF(Today()-Due_Date__c&gt;30  &amp;&amp; Today()-Due_Date__c&lt;=60, &apos;31-60&apos;, 

 IF(Today()-Due_Date__c&gt;60  &amp;&amp; Today()-Due_Date__c&lt;=90, &apos;61-90&apos;, 
 
IF(Today()-Due_Date__c&gt;90  &amp;&amp; Today()-Due_Date__c&lt;=120, &apos;91-120&apos;, &apos;&gt;121&apos;) 

) 

) 

)
, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Outstanding (Days)</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Balance_Outstanding__c</fullName>
        <label>Balance Outstanding</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X0_30_Days_Old__c</fullName>
        <defaultValue>0</defaultValue>
        <label>0-30 Days Old</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X120_Days_Old__c</fullName>
        <defaultValue>0</defaultValue>
        <label>&gt; 120 Days Old</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X31_60_Days_Old__c</fullName>
        <defaultValue>0</defaultValue>
        <label>31-60 Days Old</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X61_90_Days_Old__c</fullName>
        <defaultValue>0</defaultValue>
        <label>61-90 Days Old</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X91_120_Days_Old__c</fullName>
        <defaultValue>0</defaultValue>
        <label>91-120 Days Old</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityOldDaysSchedluer.cls
global class OpportunityOldDaysSchedluer implements schedulable  {
    global void execute(SchedulableContext stx)
    {
        checkAndUpdateDaysField();
    }
    
    public static void checkAndUpdateDaysField()
    {
        List<ContentVersion> processCvList = new List<ContentVersion>();
        List<id> ContentDocumentIds = new List<id>();
        Map<id, ContentVersion> cvMap = new Map<id, ContentVersion>();
        Map<id, id> cdlMap = new Map<id, id>();
        Map<id, id> cvOppMap = new Map<id, id>();
        
        List<id> cdLists = new List<id>();
        
        for(ContentVersion cvs:[SELECT Id, title, ContentDocumentId, Amount__c, Days_Outstanding__c from ContentVersion])
        {
            if(cvs.title.contains('Invoice#'))
            {
                cdLists.add(cvs.ContentDocumentId);
                processCvList.add(cvs);
                cvMap.put(cvs.id, cvs);
            }
        }
        
        for(ContentDocumentLink cdl: [Select id, ContentDocumentId, linkedEntityId from ContentDocumentLink where ContentDocumentId=:cdLists])
        {
            ContentDocumentIds.add(cdl.ContentDocumentId);
            cdlMap.put(cdl.ContentDocumentId, cdl.linkedEntityId);
        }
        
        for(ContentVersion cv:processCvList)
        {
            cvOppMap.put(cv.id, cdlMap.get(cv.ContentDocumentId));
        }
        
        if(processCvList.size()>0)
        {
             List<Opportunity> opps = [SELECT Id, Name, StageName,Balance_Outstanding__c, X0_30_Days_Old__c, X31_60_Days_Old__c, X61_90_Days_Old__c, X91_120_Days_Old__c, X120_Days_Old__c 
                                          FROM Opportunity];  
            OpportuniytSchedulerHandler.updateRecords(opps,0,null);
//            OpportuniytSchedulerHandler.updateOppofInvoice(processCvList, cvMap, cvOppMap,'');
        }
    }
}