src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Excpected_Billing_Date__c</fullName>
        <label>Expected Billing Date</label>
        <type>Date</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvoiceDateUpdateScheduler.cls
public class InvoiceDateUpdateScheduler implements Queueable{
    
    public Map<Id,Date> invoicesToUpdate {get;set;}
    
    public InvoiceDateUpdateScheduler(Map<Id,Date> newInvoices){
        invoicesToUpdate = newInvoices;
    }
    
    public void execute(QueueableContext QC){
        List<Invoice__c> toUpdate = new List<Invoice__c>();
        for(Invoice__c inv : [Select Id,Excpected_Billing_Date__c from Invoice__c where Id =:invoicesToUpdate.keySet()]){
            inv.Excpected_Billing_Date__c = invoicesToUpdate.get(inv.Id);
            toUpdate.add(inv);
        }
        update toUpdate;
    }
}