src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>proposal_issued_to_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal issued to 1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (proposal issued to 1)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/scriptBatch.cls
global class scriptBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id FROM Opportunity WHERE proposal_issued_to_1__c != null AND AccountId != null AND stageName = \'Closed Won\''
        );
    }
    global void execute(Database.BatchableContext bc, List<Opportunity> records){
        List<Id> oppIds = new List<Id>();
        for(Opportunity opp : records){
            oppIds.add(opp.Id);
        }
        Update [Select id from Invoice__c where Opportunity__c = :oppIds];
    }    
    global void finish(Database.BatchableContext bc){
        
    }
    public static void testPass(){
        Integer i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
    }    
}