src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_Frame__c</fullName>
        <label>Time Frame (Weeks)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bid_Documents_Construction_Documents__c</fullName>
        <label>Bid Documents/ Construction Documents</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Construction_Admin__c</fullName>
        <label>Construction Admin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DOB_Approval_1__c</fullName>
        <label>DOB Approval 1</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DOB_Filing_Set_1__c</fullName>
        <label>DOB Filing Set 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee_Schedule_Stage_Count__c</fullName>
        <label>Fee Schedule Stage Count</label>
        <summaryForeignKey>Invoice__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Punchlist__c</fullName>
        <label>Punchlist</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Retainer1__c</fullName>
        <label>Retainer1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Schematic_Design_SD_1__c</fullName>
        <label>Schematic Design (SD) 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TF_CA__c</fullName>
        <defaultValue>52</defaultValue>
        <label>TF - CA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TF_DD_CD__c</fullName>
        <defaultValue>4</defaultValue>
        <label>TF - DD/CD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TF_DOB_App__c</fullName>
        <defaultValue>8</defaultValue>
        <label>TF - DOB App</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TF_DOB_Filing__c</fullName>
        <defaultValue>6</defaultValue>
        <label>TF - DOB Filing</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TF_Punch__c</fullName>
        <defaultValue>2</defaultValue>
        <label>TF - Punch</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TF_SD__c</fullName>
        <defaultValue>4</defaultValue>
        <label>TF - SD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExistingRecordScript.cls
global class ExistingRecordScript implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('Select Id, TF_SD__c, TF_DOB_Filing__c, TF_DOB_App__c, TF_DD_CD__c, TF_CA__c, TF_Punch__c, Retainer1__c,'+
                                        'Schematic_Design_SD_1__c, DOB_Filing_Set_1__c,'+
                                        'DOB_Approval_1__c, Bid_Documents_Construction_Documents__c, Construction_Admin__c, Punchlist__c from '+
                                        'Opportunity where Fee_Schedule_Stage_Count__c=0');
    }
    
    global void execute(Database.BatchableContext BC, List<Opportunity> records){
        
        List<Invoice__c> defaultInvoices=new List<Invoice__c>();
        
        for(Opportunity opp: records) {
            
            defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_1, Time_Frame__c='To Start Project', Default__c=true,
                                               Fee__c=opp.Retainer1__c, Opportunity__c=opp.Id));
            
            defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_2, Time_Frame__c=String.valueof(opp.TF_SD__c), Default__c=true,
                                               Fee__c=opp.Schematic_Design_SD_1__c, Opportunity__c=opp.Id));
            
            defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_3, Time_Frame__c=String.valueof(opp.TF_DOB_Filing__c), Default__c=true,
                                               Fee__c=opp.DOB_Filing_Set_1__c, Opportunity__c=opp.Id));
            
            defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_4, Time_Frame__c=String.valueof(opp.TF_DOB_App__c), Default__c=true,
                                               Fee__c=opp.DOB_Approval_1__c, Opportunity__c=opp.Id));
            
            defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_5, Time_Frame__c=String.valueof(opp.TF_DD_CD__c), Default__c=true,
                                               Fee__c=opp.Bid_Documents_Construction_Documents__c, Opportunity__c=opp.Id));
            
            defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_6, Time_Frame__c=String.valueof(opp.TF_CA__c), Default__c=true,
                                               Fee__c=opp.Construction_Admin__c, Opportunity__c=opp.Id));
            
            defaultInvoices.add(new Invoice__c(Name=System.label.Default_Stage_7, Time_Frame__c=String.valueof(opp.TF_Punch__c), Default__c=true,
                                               Fee__c=opp.Punchlist__c, Opportunity__c=opp.Id));
            
        }
        
        insert defaultInvoices;
        
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
}