src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AddressChangesCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>AddressChangesCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>proposal_issued_to_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal issued to 1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (proposal issued to 1)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>proposal_issued_to_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal issued to 2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (proposal issued to 2)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactTriggerHandler.cls
public class ContactTriggerHandler {
    public static void triggerAddressChange(List<Contact> newContacts,Map<Id,Contact> oldContacts){
        Set<Id> contactsWithChangedAddress = new Set<Id>();
        for(Contact con : newContacts){
            if(con.MailingCity != oldContacts.get(con.Id).MailingCity ||
               con.MailingCountry != oldContacts.get(con.Id).MailingCountry ||
               con.MailingPostalCode != oldContacts.get(con.Id).MailingPostalCode ||
               con.MailingState != oldContacts.get(con.Id).MailingState ||
               con.MailingStreet != oldContacts.get(con.Id).MailingStreet ||
               con.OtherCity != oldContacts.get(con.Id).OtherCity ||
               con.OtherCountry != oldContacts.get(con.Id).OtherCountry ||
               con.OtherPostalCode != oldContacts.get(con.Id).OtherPostalCode ||
               con.OtherState != oldContacts.get(con.Id).OtherState ||
               con.OtherStreet != oldContacts.get(con.Id).OtherStreet){
                   contactsWithChangedAddress.add(con.Id);
               }
        }
        
        List<Opportunity> oppsToUpdate = new List<Opportunity>();
        for(Opportunity opp : [Select Id,AddressChangesCount__c from Opportunity 
                               where proposal_issued_to_1__c = :contactsWithChangedAddress 
                               or proposal_issued_to_2__c = :contactsWithChangedAddress]){
            opp.AddressChangesCount__c = opp.AddressChangesCount__c == null ? 1 : opp.AddressChangesCount__c + 1;
            oppsToUpdate.add(opp);
        }
        
        update oppsToUpdate;
    }
}