src/objects/QB_Credentials__c.object
<CustomObject>
    <fields>
        <fullName>Access_token__c</fullName>
        <label>Access token</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RealMId__c</fullName>
        <label>RealMId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_token__c</fullName>
        <label>Refresh token</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>QB Credentials</label>
    <nameField>
        <displayFormat>QBC-{00000}</displayFormat>
        <label>QB Credential Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QB Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_QuickbookConnection.cls
@isTest
public class Test_QuickbookConnection {
    
    @TestSetup static void createData()
    {
        QB_Credentials__c qb=new QB_Credentials__c(Access_token__c='123', Refresh_token__c='123', realmid__c='123');
        insert qb;
    }
    
    
    @isTest static void Test1()
    {
        Test.startTest();
        List<QB_Credentials__c> qbcList=[Select Id, Access_token__c, Refresh_token__c,
                                         realmid__c from QB_Credentials__c];
        
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Test.setCurrentPage(new PageReference('apex/QuickbookAuthentication')); 
        ApexPages.currentPage().getParameters().put('code', '123');
        ApexPages.currentPage().getParameters().put('realmid', '456');        
        
        QuickbookConnection qc=new QuickbookConnection();
        qc.getQbCred();
        qc.doFetchAccessToken();
        qc.doAuthorizationQuickBooks();
        Test.stopTest();
    }
    
}